services:

  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    networks:
      - mongodb

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: rag
      ME_CONFIG_MONGODB_ADMINPASSWORD: rag
      ME_CONFIG_MONGODB_URL: mongodb://rag:rag@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - mongodb

networks:
  mongodb:

# Define named volumes
volumes:
  mongo-data:
    driver: local
